double    x1 = 0.5;
        double    y1 = 0.5;
        double    distx1;
        double    distx2;
        double    xmin1;
        double    xmax1;
        double    xmin2;
        double    xmax2;
        double    disty1;
        double    disty2;
        double    ymin1;
        double    ymax1;
        double    ymin2;
        double    ymax2;

        zoom *= 0.99;
        x1 = all->p->x1;
        x2 = all->p->x2;
        y1 = all->p->y1;
        y2 = all->p->y2;
        distx1 = x1 - xmin1;
        distx2 = distx1 * zoom;
        disty1 = y1 - ymin1;
        disty2 = disty1 * zoom;
        nx1 = x1 - distx2;
        nx2 = xmin2 + (xmax1 - xmin1) * zoom;
        ny1 = y1 - disty2;
        ny2 = ymin2 + (ymax1 - ymin1) * zoom;
        all->p->x1 = nx1;
        all->p->x2 = nx2;
        all->p->y1 = ny2;
        all->p->y2 = ny2;